version: '2'

networks:
  gocd:

services:
  master:
    image: gocd/gocd-server:v17.6.0
    restart: always
    networks:
      gocd:
    ports: 
      - 8153:8153
    environment:
      - AGENT_AUTO_REGISTER_KEY=somethingunique
      - MSG_TIME=0

  agent:
    image: gocd/gocd-agent-centos-7:v17.6.0 
    restart: always
    networks:
      gocd:
    depends_on:
      - master
    volumes:
      - build_data:/godata
    environment:
      - GO_SERVER_URL=https://master:8154/go
      - AGENT_AUTO_REGISTER_KEY=somethingunique
      - AGENT_AUTO_REGISTER_RESOURCES=docker
      - AGENT_AUTO_REGISTER_ENVIRONMENTS=docker
      - AGENT_AUTO_REGISTER_HOSTNAME
      - DOCKER_HOST=tcp://127.0.0.1:2375

  dind:
    image: docker:stable-dind
    restart: always
    network_mode: 'service:agent'
    volumes:
      - build_data:/godata
    privileged: true

volumes:
  build_data: {}
