apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: gocd-agent
spec:
  replicas: 2
  revisionHistoryLimit: 1
  strategy:
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  selector:
    matchLabels:
      app: agent
      tier: gocd
  template:
    metadata:
      labels:
        app: agent
        tier: gocd
    spec:
      volumes:
      - name: build-data
        emptyDir: {}
      restartPolicy: Always
      containers:
      - name: dind 
        securityContext:
          privileged: true
        image: docker:stable-dind
        imagePullPolicy: Always
        volumeMounts:
        - name: build-data
          mountPath: /godata 
      - name: agent 
        image: eu.gcr.io/peopledata-product-team/kube-gocd-agent:latest 
        imagePullPolicy: Always
        volumeMounts:
        - name: build-data
          mountPath: /godata
        env:
        - name: DOCKER_HOST
          value: 'tcp://127.0.0.1:2375'
        - name: GO_SERVER_URL
          value: 'https://gocd-master-internal:8154/go'
        - name: AGENT_AUTO_REGISTER_KEY
          valueFrom:
            secretKeyRef:
              name: kube-gocd
              key: agent_key
        - name: AGENT_AUTO_REGISTER_RESOURCES
          value:  
        - name: AGENT_AUTO_REGISTER_ENVIRONMENTS
          value:  
