apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: gocd-master
spec:
  replicas: 1
  revisionHistoryLimit: 1
  strategy:
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  selector:
    matchLabels:
      app: master
      tier: gocd
  template:
    metadata:
      labels:
        app: master
        tier: gocd
    spec:
      restartPolicy: Always
      containers:
      - name: agent 
        image: eu.gcr.io/peopledata-product-team/kube-gocd-master:latest 
        imagePullPolicy: Always
        env:
        - name: AGENT_AUTO_REGISTER_KEY
          valueFrom:
            secretKeyRef:
              name: kube-gocd 
              key: agent_key
        - name: GOCD_USER
          valueFrom:
            secretKeyRef:
              name: kube-gocd
              key: user
        - name: GOCD_PASSWORD
          valueFrom:
            secretKeyRef:
              name: kube-gocd 
              key: pass
        ports:
        - containerPort: 8153
        - containerPort: 8154
---
apiVersion: v1
kind: Service
metadata:
  name: gocd-master-internal
spec:
  ports:
  - port: 8154
    name: agent
    targetPort: 8154
  - port: 8153
    name: http
    targetPort: 8153
  selector:
    app: master
    tier: gocd
---
apiVersion: v1
kind: Service
metadata:
  name: gocd-master-external
spec:
  type: LoadBalancer
  ports:
  - port: 80
    name: http
    targetPort: 8153
  selector:
    app: master
    tier: gocd
